[2025-10-11T06:03:08.065+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T06:03:08.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_flow.load_ratings scheduled__1998-02-15T00:00:00+00:00 [queued]>
[2025-10-11T06:03:08.144+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_flow.load_ratings scheduled__1998-02-15T00:00:00+00:00 [queued]>
[2025-10-11T06:03:08.145+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-11T06:03:08.172+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_ratings> on 1998-02-15 00:00:00+00:00
[2025-10-11T06:03:08.189+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8791) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-11T06:03:08.192+0000] {standard_task_runner.py:64} INFO - Started process 8797 to run task
[2025-10-11T06:03:08.190+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline_flow', 'load_ratings', 'scheduled__1998-02-15T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp8pjlyrus']
[2025-10-11T06:03:08.194+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask load_ratings
[2025-10-11T06:03:08.289+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_flow.load_ratings scheduled__1998-02-15T00:00:00+00:00 [running]> on host 321597a50810
[2025-10-11T06:03:08.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='oluwaseyiogundimu10@gmail.com' AIRFLOW_CTX_DAG_OWNER='seyi' AIRFLOW_CTX_DAG_ID='pipeline_flow' AIRFLOW_CTX_TASK_ID='load_ratings' AIRFLOW_CTX_EXECUTION_DATE='1998-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__1998-02-15T00:00:00+00:00'
[2025-10-11T06:03:08.501+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T06:03:08.534+0000] {transform.py:91} INFO - Starting transformations for ratings..
[2025-10-11T06:03:08.536+0000] {read_write_buckets.py:22} INFO - Reading ratings.csv from movie-pipeline-bronze bucket.
[2025-10-11T06:03:08.778+0000] {s3_client.py:30} INFO - âœ… Successfully initialized S3 client.
[2025-10-11T06:03:15.985+0000] {read_write_buckets.py:34} INFO - Successfully read ratings.csv into DataFrame. Shape: (100000, 4)
[2025-10-11T06:03:16.034+0000] {transform.py:118} INFO - Weekly run: filtering 3062 rating records from 1998-02-15 to 1998-02-22
[2025-10-11T06:03:16.036+0000] {watermarks.py:25} INFO - Reading watermarks from S3 Bronze bucket...
[2025-10-11T06:03:16.280+0000] {watermarks.py:30} INFO - Successfully read existing watermarks.
[2025-10-11T06:03:16.282+0000] {transform.py:126} INFO - Applying watermark filter for ratings..
[2025-10-11T06:03:16.293+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/../pipeline/b_silver/transform.py:133 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-10-11T06:03:16.297+0000] {transform.py:141} INFO - Filtered ratings to 3062 new records after watermark 1997-09-30 23:54:47.
[2025-10-11T06:03:16.299+0000] {read_write_buckets.py:22} INFO - Reading ratings/1998-02.csv from movie-pipeline-silver bucket.
[2025-10-11T06:03:17.419+0000] {read_write_buckets.py:38} ERROR - Error reading ratings/1998-02.csv from S3 Bronze bucket: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Traceback (most recent call last):
  File "/opt/airflow/dags/../pipeline/b_silver/read_write_buckets.py", line 28, in read_file
    response = client.get_object(Bucket=bucket_name, Key=object_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-10-11T06:03:17.437+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/../pipeline/b_silver/transform.py:162 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-10-11T06:03:17.438+0000] {read_write_buckets.py:50} INFO - Writing ratings/1998-02.csv to movie-pipeline-silver bucket.
[2025-10-11T06:03:18.540+0000] {read_write_buckets.py:66} INFO - Successfully wrote ratings/1998-02.csv to Silver bucket.
[2025-10-11T06:03:18.542+0000] {watermarks.py:48} INFO - Updating watermarks in S3...
[2025-10-11T06:03:18.544+0000] {watermarks.py:25} INFO - Reading watermarks from S3 Bronze bucket...
[2025-10-11T06:03:18.826+0000] {watermarks.py:30} INFO - Successfully read existing watermarks.
[2025-10-11T06:03:19.465+0000] {watermarks.py:76} INFO - Watermarks updated successfully in S3.
[2025-10-11T06:03:19.467+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-11T06:03:19.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T06:03:19.479+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline_flow, task_id=load_ratings, run_id=scheduled__1998-02-15T00:00:00+00:00, execution_date=19980215T000000, start_date=20251011T060308, end_date=20251011T060319
[2025-10-11T06:03:19.520+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-11T06:03:19.553+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-11T06:03:19.556+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
